Cloudsql auth proxy
pachyderm/helmchart pull request #195
Opened 2021-06-28 20:42 UTC by seslattery

2021-06-29 12:39 UTC, chainlink requested changes
One small comment, but otherwise looking good! Can you add a section to the GCP test to exercise these values?

2021-06-29 12:39 UTC, chainlink commented on pachyderm/values.yaml
> +          memory: "2Gi"
We generally haven't hardcoded requests and limits and left that as an exercise for the user depending on their cluster environment.

2021-06-29 17:21 UTC, chainlink approved these changes
Looks good!

2021-06-29 17:23 UTC, seslattery commented
> One small comment, but otherwise looking good! Can you add a section to the GCP test to exercise these values?

Will add test soon, going to e2e this on Hub before I write the test.

2021-06-30 23:10 UTC, seslattery commented
I've moved the proxy over to a deployment/service, and wired up workload identity. (I still owe a test too)  @chainlink PTAL

2021-07-27 17:01 UTC, chainlink commented
Going to close this one out, as it's merged into the main repo

2021-07-27 17:01 UTC, closed without merging